/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Exceptions.CodigoCadastrado;
import Exceptions.EmptyCampException;
import Exceptions.NotFoundItemException;
import JavaBeans.Produto;
import Actions.Verificacao;
import Exceptions.NomeCadastrado;
import JavaBeans.ConexaoBD;
import com.lowagie.text.Image;
import com.sun.media.sound.InvalidFormatException;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Danielle S. França
 */
public class CadastroProduto extends javax.swing.JFrame {

    Produto produto;
    DecimalFormat real;
    String caminho;

    public CadastroProduto() {
        initComponents();
        setLocationRelativeTo(null);
        produto = new Produto();
        real = new DecimalFormat("R$ ,##0.00;(,##0.00)");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void limpaTela() {
        tcodigo2.setText("");
        tnome2.setText("");
        tquantidade2.setText("");
        tvalor2.setText("");
        ttotal.setText("");
        timagem.setText("");
        imagemSelecionada.setIcon(new ImageIcon());
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        nome2 = new javax.swing.JLabel();
        tnome2 = new javax.swing.JTextField();
        codigo2 = new javax.swing.JLabel();
        tcodigo2 = new javax.swing.JTextField();
        quantidade2 = new javax.swing.JLabel();
        tquantidade2 = new javax.swing.JTextField();
        valor = new javax.swing.JLabel();
        total2 = new javax.swing.JLabel();
        ttotal = new javax.swing.JLabel();
        tvalor2 = new javax.swing.JFormattedTextField();
        imagem = new javax.swing.JLabel();
        timagem = new javax.swing.JTextField();
        selecionarFoto = new javax.swing.JButton();
        mostrarImagem = new javax.swing.JPanel();
        imagemSelecionada = new javax.swing.JLabel();
        limpar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        salvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro do Produto");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(153, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        nome2.setText("Nome:");

        codigo2.setText("Código:");

        quantidade2.setText("Quantidade:");

        tquantidade2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tquantidade2KeyReleased(evt);
            }
        });

        valor.setText("Valor:");

        total2.setText("Total:");

        tvalor2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##0.00;(,##0.00)"))));
        tvalor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tvalor2KeyReleased(evt);
            }
        });

        imagem.setText("Imagem:");

        timagem.setEditable(false);
        timagem.setBackground(new java.awt.Color(255, 255, 255));

        selecionarFoto.setText("...");
        selecionarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarFotoActionPerformed(evt);
            }
        });

        mostrarImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout mostrarImagemLayout = new javax.swing.GroupLayout(mostrarImagem);
        mostrarImagem.setLayout(mostrarImagemLayout);
        mostrarImagemLayout.setHorizontalGroup(
            mostrarImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrarImagemLayout.createSequentialGroup()
                .addComponent(imagemSelecionada, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mostrarImagemLayout.setVerticalGroup(
            mostrarImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrarImagemLayout.createSequentialGroup()
                .addComponent(imagemSelecionada, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(valor)
                                .addGap(18, 18, 18)
                                .addComponent(tvalor2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(nome2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tnome2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(quantidade2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tquantidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(total2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(codigo2)
                                .addGap(18, 18, 18)
                                .addComponent(tcodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(imagem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(timagem, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(selecionarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(mostrarImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(mostrarImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo2)
                    .addComponent(tcodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome2)
                    .addComponent(tnome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imagem)
                    .addComponent(timagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecionarFoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidade2)
                    .addComponent(tquantidade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor)
                    .addComponent(tvalor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(total2)
                    .addComponent(ttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(salvar)
                        .addGap(18, 18, 18)
                        .addComponent(limpar)
                        .addGap(18, 18, 18)
                        .addComponent(voltar)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltar)
                    .addComponent(salvar)
                    .addComponent(limpar))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        try {
            Verificacao verificar = new Verificacao();
            if (tcodigo2.getText().equals("")) {
                produto.setCodigo(-1);
            } else {
                produto.setCodigo(Integer.parseInt(tcodigo2.getText()));
                verificar.verificarCodigo(Integer.parseInt(tcodigo2.getText()));
            }
            if (tvalor2.getText().equals("")) {
                produto.setValor(-1);
            } else {
                String valor = tvalor2.getText();
                valor = valor.replace(".", "");
                valor = valor.replace(",", ".");
                produto.setValor(Double.parseDouble(valor));
            }
            verificar.verificarNome(tnome2.getText());
            produto.setNome(tnome2.getText());
            if (tquantidade2.getText().equals("")) {
                produto.setQuantidade(0);
            } else {
                produto.setQuantidade(Integer.parseInt(tquantidade2.getText()));
            }
            produto.setImagem(caminho);
            ConexaoBD conexao = new ConexaoBD();
            conexao.setProduto(1, produto);
            limpaTela();
            JOptionPane.showMessageDialog(null, "Seus dados foram cadastrados!", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);

        } catch (EmptyCampException ex) {
            JOptionPane.showMessageDialog(null, "Você deve preencher os campos CÓDIGO,NOME e VALOR para realizar o cadastro!", "ERRO", JOptionPane.ERROR_MESSAGE);
        } catch (CodigoCadastrado ex) {
            JOptionPane.showMessageDialog(null, "Esse CÓDIGO já está cadastrado no sistema!", "ERRO!", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Nos campos CÓDIGO, QUANTIDADE e VALOR você deve digitar somente números!", "ERRO!", JOptionPane.ERROR_MESSAGE);
        } catch (NomeCadastrado ex){
            JOptionPane.showMessageDialog(null, "Já existe um produto cadastrado com esse NOME no sistema!","ERRO!",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_salvarActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        limpaTela();
    }//GEN-LAST:event_limparActionPerformed

    private void tquantidade2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tquantidade2KeyReleased
        try {
            if (tquantidade2.getText().equals("")) {
                produto.setQuantidade(0);
            } else {
                produto.setQuantidade(Integer.parseInt(tquantidade2.getText()));
            }
            produto.setTotal();
            ttotal.setText(real.format(produto.getTotal()));
        } catch (NumberFormatException ex) {
        }


    }//GEN-LAST:event_tquantidade2KeyReleased

    private void tvalor2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tvalor2KeyReleased
        try {
            if (tvalor2.getText().equals("")) {
                produto.setValor(0);
            } else {
                String valor = tvalor2.getText();
                valor.replace(",", ".");
                produto.setValor(Double.parseDouble(valor));
            }
            produto.setTotal();
            ttotal.setText(real.format(produto.getTotal()));
        } catch (NumberFormatException ex) {
        }
    }//GEN-LAST:event_tvalor2KeyReleased

    private void selecionarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarFotoActionPerformed
        try {
            Selecionar selecionar = new Selecionar(null, 3, null, null);
            if (selecionar.pegarCaminho() != null) {
                if (selecionar.pegarNome().substring(selecionar.pegarNome().lastIndexOf('.') + 1).equals("jpg") || selecionar.pegarNome().substring(selecionar.pegarNome().lastIndexOf('.') + 1).equals("png")) {
                    timagem.setText(selecionar.pegarCaminho());
                    caminho = "resources/fotosProdutos/" + selecionar.pegarNome();
                    BufferedImage image = ImageIO.read(new File("resources\\fotosProdutos\\" + selecionar.pegarNome()));
                    imagemSelecionada.setIcon(new ImageIcon(image.getScaledInstance(mostrarImagem.getWidth(), mostrarImagem.getHeight(), 1)));
                } else {
                    JOptionPane.showMessageDialog(null, "Você deve selecionar uma imagem nos formatos jpg, jpge ou png!", "ERRO!", JOptionPane.ERROR_MESSAGE);
                }
            }
            selecionar.fechar();
        } catch (Exception ex) {
            Logger.getLogger(CadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_selecionarFotoActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codigo2;
    private javax.swing.JLabel imagem;
    private javax.swing.JLabel imagemSelecionada;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton limpar;
    private javax.swing.JPanel mostrarImagem;
    private javax.swing.JLabel nome2;
    private javax.swing.JLabel quantidade2;
    private javax.swing.JButton salvar;
    private javax.swing.JButton selecionarFoto;
    private javax.swing.JTextField tcodigo2;
    private javax.swing.JTextField timagem;
    private javax.swing.JTextField tnome2;
    private javax.swing.JLabel total2;
    private javax.swing.JTextField tquantidade2;
    private javax.swing.JLabel ttotal;
    private javax.swing.JFormattedTextField tvalor2;
    private javax.swing.JLabel valor;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
