/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Actions.Verificacao;
import Exceptions.CodigoCadastrado;
import Exceptions.EmptyBankException;
import Exceptions.EmptyCampException;
import Exceptions.NomeCadastrado;
import Exceptions.NotFoundItemException;
import JavaBeans.ConexaoBD;
import JavaBeans.Produto;
import com.sun.media.sound.InvalidFormatException;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Danielle S. França
 */
public class EditarProduto extends javax.swing.JFrame {

    Produto produtoProcurado;
    DecimalFormat real;
    String caminho;
    DecimalFormat val;
    JFrame parent;

    public EditarProduto(Produto produtoProcurado, JFrame p) {
        this.parent = p;
        real = new DecimalFormat("R$ ,##0.00;(,##0.00)");
        val = new DecimalFormat("##0.00;(,##0.00)");
        this.produtoProcurado = produtoProcurado;
        initComponents();
        preencherCampos();
        setLocationRelativeTo(null);
        UIManager.put("OptionPane.yesButtonText", "Sim");
        UIManager.put("OptionPane.noButtonText", "Não");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void preencherCampos() {
        tcodigo2.setText(Integer.toString(produtoProcurado.getCodigo()));
        tnome2.setText(produtoProcurado.getNome());
        tvalor2.setText(val.format(produtoProcurado.getValor()));
        tquantidade2.setText(Integer.toString(produtoProcurado.getQuantidade()));
        ttotal.setText(real.format(produtoProcurado.getTotal()));
        caminho = produtoProcurado.getImagem();
        if (produtoProcurado.getImagem() != null) {
            File file = new File(produtoProcurado.getImagem());
            if (file.exists()) {
                timagem.setText(produtoProcurado.getImagem());
                BufferedImage image = null;
                try {
                    image = ImageIO.read(new File(produtoProcurado.getImagem()));
                } catch (IOException ex) {
                }
                imagemSelecionada.setIcon(new ImageIcon(image.getScaledInstance(mostrarImagem.getWidth(), mostrarImagem.getHeight(), 1)));
            }
        }
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        voltar = new javax.swing.JButton();
        salvar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        nome2 = new javax.swing.JLabel();
        tnome2 = new javax.swing.JTextField();
        codigo2 = new javax.swing.JLabel();
        tcodigo2 = new javax.swing.JTextField();
        quantidade2 = new javax.swing.JLabel();
        tquantidade2 = new javax.swing.JTextField();
        valor = new javax.swing.JLabel();
        total2 = new javax.swing.JLabel();
        ttotal = new javax.swing.JLabel();
        imagem = new javax.swing.JLabel();
        timagem = new javax.swing.JTextField();
        selecionarFoto = new javax.swing.JButton();
        mostrarImagem = new javax.swing.JPanel();
        imagemSelecionada = new javax.swing.JLabel();
        tvalor2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Produto");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(153, 255, 255));

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        salvar.setText("Editar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        nome2.setText("Nome:");

        codigo2.setText("Código:");

        quantidade2.setText("Quantidade:");

        tquantidade2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tquantidade2KeyReleased(evt);
            }
        });

        valor.setText("Valor:");

        total2.setText("Total:");

        imagem.setText("Imagem:");

        timagem.setEditable(false);
        timagem.setBackground(new java.awt.Color(255, 255, 255));

        selecionarFoto.setText("...");
        selecionarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarFotoActionPerformed(evt);
            }
        });

        mostrarImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout mostrarImagemLayout = new javax.swing.GroupLayout(mostrarImagem);
        mostrarImagem.setLayout(mostrarImagemLayout);
        mostrarImagemLayout.setHorizontalGroup(
            mostrarImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrarImagemLayout.createSequentialGroup()
                .addComponent(imagemSelecionada, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mostrarImagemLayout.setVerticalGroup(
            mostrarImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrarImagemLayout.createSequentialGroup()
                .addComponent(imagemSelecionada, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tvalor2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tvalor2FocusLost(evt);
            }
        });
        tvalor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tvalor2KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(nome2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tnome2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(total2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(codigo2)
                                .addGap(18, 18, 18)
                                .addComponent(tcodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(imagem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(timagem, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(selecionarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(valor)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tvalor2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(quantidade2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tquantidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(mostrarImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(mostrarImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo2)
                    .addComponent(tcodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome2)
                    .addComponent(tnome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imagem)
                    .addComponent(timagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecionarFoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidade2)
                    .addComponent(tquantidade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor)
                    .addComponent(tvalor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(total2)
                    .addComponent(ttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(salvar)
                        .addGap(18, 18, 18)
                        .addComponent(voltar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvar)
                    .addComponent(voltar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        try {
            Verificacao verificar = new Verificacao();
            if (tcodigo2.getText().equals("")) {
                produtoProcurado.setCodigo(-1);
            } else if (Integer.parseInt(tcodigo2.getText()) != produtoProcurado.getCodigo()) {
                verificar.verificarCodigo(Integer.parseInt(tcodigo2.getText()));
                produtoProcurado.setCodigo(Integer.parseInt(tcodigo2.getText()));
            }
            if (tvalor2.getText().equals("")) {
                produtoProcurado.setValor(-1);
            } else {
                Long d = null;
                try {
                    d = (Long) val.parse(tvalor2.getText());
                } catch (ParseException ex) {
                    Logger.getLogger(EditarProduto.class.getName()).log(Level.SEVERE, null, ex);
                }
                produtoProcurado.setValor(d);
            }
            if(!produtoProcurado.getNome().equals(tnome2.getText())){
                verificar.verificarNome(tnome2.getText());
            }
            produtoProcurado.setNome(tnome2.getText());
            if (tquantidade2.getText().equals("")) {
                produtoProcurado.setQuantidade(0);
            } else {
                produtoProcurado.setQuantidade(Integer.parseInt(tquantidade2.getText()));
            }
            produtoProcurado.setImagem(caminho);
            int res = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja alterar esses dados?", "AVISO", JOptionPane.YES_NO_OPTION);
            if (res == JOptionPane.YES_OPTION) {
                ConexaoBD conexao = new ConexaoBD();
                conexao.setProduto(2, produtoProcurado);
                try {
                    Pesquisar pesquisar = (Pesquisar) parent;
                    pesquisar.buscar();
                } catch (NotFoundItemException ex) {
                } catch (EmptyBankException ex) {
                }
                JOptionPane.showMessageDialog(null, "Dados alterados com sucesso!", "AVISO!", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (EmptyCampException ex) {
            JOptionPane.showMessageDialog(null, "Você deve preencher os campos CÓDIGO,NOME e VALOR para realizar o cadastro!", "ERRO", JOptionPane.ERROR_MESSAGE);
        } catch (CodigoCadastrado ex) {
            JOptionPane.showMessageDialog(null, "Esse CÓDIGO já está cadastrado no sistema!", "ERRO!", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Nos campos CÓDIGO, QUANTIDADE e VALOR você deve digitar somente números!", "ERRO!", JOptionPane.ERROR_MESSAGE);
        } catch (NomeCadastrado ex) {
            JOptionPane.showMessageDialog(null, "Já existe um produto cadastrado com esse NOME no sistema!", "ERRO!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_salvarActionPerformed

    private void tquantidade2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tquantidade2KeyReleased
        try {
            if (tquantidade2.getText().equals("")) {
                produtoProcurado.setQuantidade(0);
            } else {
                produtoProcurado.setQuantidade(Integer.parseInt(tquantidade2.getText()));
            }
            produtoProcurado.setTotal();
            ttotal.setText(real.format(produtoProcurado.getTotal()));
        } catch (NumberFormatException ex) {
        }

    }//GEN-LAST:event_tquantidade2KeyReleased

    private void selecionarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarFotoActionPerformed
        try {
            Selecionar selecionar = new Selecionar(null, 3, null, null);
            if (selecionar.pegarCaminho() != null) {
                if (selecionar.pegarNome().substring(selecionar.pegarNome().lastIndexOf('.') + 1).equals("jpg") || selecionar.pegarNome().substring(selecionar.pegarNome().lastIndexOf('.') + 1).equals("png") || selecionar.pegarNome().substring(selecionar.pegarNome().lastIndexOf('.') + 1).equals("jpge")) {
                    timagem.setText(selecionar.pegarCaminho());
                    BufferedImage image = ImageIO.read(new File("resources\\fotosProdutos\\" + selecionar.pegarNome()));
                    caminho = "resources/fotosProdutos/" + selecionar.pegarNome();
                    imagemSelecionada.setIcon(new ImageIcon(image.getScaledInstance(mostrarImagem.getWidth(), mostrarImagem.getHeight(), 1)));
                    selecionar.fechar();
                } else {
                    JOptionPane.showMessageDialog(null, "Você deve selecionar uma imagem nos formatos jpg,jpge ou png!", "ERRO!", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(CadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_selecionarFotoActionPerformed

    private void tvalor2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tvalor2FocusLost
        tvalor2.setText(val.format(produtoProcurado.getValor()));
    }//GEN-LAST:event_tvalor2FocusLost

    private void tvalor2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tvalor2KeyReleased
        try {
            if (tvalor2.getText().equals("")) {
                produtoProcurado.setValor(0);
            } else {
                Long d = null;
                try {
                    d = (Long) val.parse(tvalor2.getText());
                } catch (ParseException ex) {
                    Logger.getLogger(EditarProduto.class.getName()).log(Level.SEVERE, null, ex);
                }
                produtoProcurado.setValor(d);
            }
            produtoProcurado.setTotal();
            ttotal.setText(real.format(produtoProcurado.getTotal()));
        } catch (NumberFormatException ex) {
        }
    }//GEN-LAST:event_tvalor2KeyReleased
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codigo2;
    private javax.swing.JLabel imagem;
    private javax.swing.JLabel imagemSelecionada;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel mostrarImagem;
    private javax.swing.JLabel nome2;
    private javax.swing.JLabel quantidade2;
    private javax.swing.JButton salvar;
    private javax.swing.JButton selecionarFoto;
    private javax.swing.JTextField tcodigo2;
    private javax.swing.JTextField timagem;
    private javax.swing.JTextField tnome2;
    private javax.swing.JLabel total2;
    private javax.swing.JTextField tquantidade2;
    private javax.swing.JLabel ttotal;
    private javax.swing.JTextField tvalor2;
    private javax.swing.JLabel valor;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
